version: '3'
services:

  i24-db:
    restart: always
    build: .
    environment:
      POSTGRES_USER: ux_data
      POSTGRES_PASSWORD: rate8&slinky
    ports:
      - '5436:5432'
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
