CREATE TABLE ux_data (
  id SERIAL PRIMARY KEY,
  event_categories VARCHAR(500)[] NOT NULL,
  event_name VARCHAR(500) NOT NULL,
  data JSON NOT NULL,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
)